HplusEcommerceWeb/Controllers/AccountController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace HplusEcommerceWeb.Controllers
{
    [Authorize]
    public class AccountController : Controller
    {
        // GET: Account
        public ActionResult Index()
        {
            return View();
        }
    }
}

HplusEcommerceWeb/Controllers/CartController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace HplusEcommerceWeb.Controllers
{
    public class CartController : Controller
    {
        // GET: Cart
        public ActionResult Index()
        {
            return View();
        }
    }
}

HplusEcommerceWeb/Controllers/HelloController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace HplusEcommerceWeb.Controllers
{
    public class HelloController : Controller
    {
        // GET: Hello
        public ActionResult Index()
        {
            return View();
        }
    }
}

HplusEcommerceWeb/Controllers/HomeController.cs
using HplusEcommerceWeb.Filters;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace HplusEcommerceWeb.Controllers
{
    public class HomeController : Controller
    {
        [CrawlerFilter]
        public ActionResult Index()
        {
            //this is used to test exception codes
            //throw new System.Exception();
            return View();
        }

        public ActionResult About()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }
    }
}

HplusEcommerceWeb/Controllers/LoginController.cs
using HplusEcommerce.Core.Entities;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Web.Security;

namespace HplusEcommerceWeb.Controllers
{
    public class LoginController : Controller
    {
        // GET: Login
        public ActionResult Index()
        {
            return View();
        }

        [HttpPost]
        //public ActionResult Index(string username, string password)
        //{
        //    if (!string.IsNullOrEmpty(username) && !string.IsNullOrEmpty(password))
        //    {
        //        FormsAuthentication.SetAuthCookie(username, false);
        //        return Redirect(FormsAuthentication.GetRedirectUrl(username, false));
        //    }

        //   // ViewBag.Failed = true;
        //    return View();
        //}

        public ActionResult Index(Login request)
        {
            if (!string.IsNullOrEmpty(request.Username) && !string.IsNullOrEmpty(request.Password))
            {
                FormsAuthentication.SetAuthCookie(request.Username, false);
                return Redirect(FormsAuthentication.GetRedirectUrl(request.Username, false));
            }

            // ViewBag.Failed = true;
            return View(request);
        }


    }
}

HplusEcommerceWeb/Controllers/ProductController.cs
using HplusEcommerce.Core.Entities;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace HplusEcommerceWeb.Controllers
{
    public class ProductController : Controller
    {
        // GET: Product
        public ActionResult Index()
        {
            return View("List");
        }


        [Route("product/{productName}")]
        public ActionResult Detail(string productName)
        {
            ViewBag.Product = new Product
            {
                Name = "Chuks Winter Jacket",
                FullPrice = 20.00M,
                CurrentPrice = 16.00M,
                PercentOff = 20,
                ImagePath = "/Content/Images/Products/1.jpg",
                StarRating = 4

            };
            // Lookup the product name in the database
            return View();
        }


    }
}

HplusEcommerceWeb/Controllers/ProductsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace HplusEcommerceWeb.Controllers
{
    public class ProductsController : Controller
    {
        // GET: Products
        public ActionResult Index()
        {
            //this is to redirect it to another controller which is the product controller
            //this is idle when url is changed and you still want to maintain the old controller

            return RedirectToAction("Index", "Product");
        }
    }
}

HplusEcommerceWeb/Views/Cart/Index.cshtml
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_LayoutNoFooter.cshtml";
}

<h3 class="h3">Cart</h3>

<div class="row">
    <div class="col-12">
        <div class="table">
            <table class="table table-striped">
                <thead>
                    <tr>
                        <th scope="col"> </th>
                        <th scope="col">Product</th>
                        <th scope="col">Available</th>
                        <th scope="col" class="text-center">Quantity</th>
                        <th scope="col" class="text-right">Price</th>
                        <th> </th>
                    </tr>
                </thead>
                <tbody>
                    <tr>
                        <td><img src="https://dummyimage.com/50x50/55595c/fff" /> </td>
                        <td>Product Name Dada</td>
                        <td>In stock</td>
                        <td><input class="form-control" type="text" value="1" /></td>
                        <td class="text-right">$124.90</td>
                        <td class="text-right"><button class="btn btn-sm btn-danger"><i class="fa fa-trash"></i> </button> </td>
                    </tr>
                    <tr>
                        <td><img src="https://dummyimage.com/50x50/55595c/fff" /> </td>
                        <td>Product Name Toto</td>
                        <td>In stock</td>
                        <td><input class="form-control" type="text" value="1" /></td>
                        <td class="text-right">$33.90</td>
                        <td class="text-right"><button class="btn btn-sm btn-danger"><i class="fa fa-trash"></i> </button> </td>
                    </tr>
                    <tr>
                        <td><img src="https://dummyimage.com/50x50/55595c/fff" /> </td>
                        <td>Product Name Titi</td>
                        <td>In stock</td>
                        <td><input class="form-control" type="text" value="1" /></td>
                        <td class="text-right">$70.00</td>
                        <td class="text-right"><button class="btn btn-sm btn-danger"><i class="fa fa-trash"></i> </button> </td>
                    </tr>
                    <tr>
                        <td></td>
                        <td></td>
                        <td></td>
                        <td></td>
                        <td>Sub-Total</td>
                        <td class="text-right">$255.90</td>
                    </tr>
                    <tr>
                        <td></td>
                        <td></td>
                        <td></td>
                        <td></td>
                        <td>Shipping</td>
                        <td class="text-right">$6.90</td>
                    </tr>
                    <tr>
                        <td></td>
                        <td></td>
                        <td></td>
                        <td></td>
                        <td><strong>Total</strong></td>
                        <td class="text-right"><strong>$346.90</strong></td>
                    </tr>
                </tbody>
            </table>
        </div>
    </div>
</div>
<div class="row">
    <div class="col-lg-4 col-lg-offset-1">
        <a href='@Url.Action("Index", "Product")' class="btn btn-primary btn-lg btn-block" role="button">Continue Shopping</a>
    </div>
    <div class="col-lg-4 col-lg-offset-2">
        <a class="btn btn-lg btn-block btn-success text-uppercase" role="button">Checkout</a>
    </div>
</div>

HplusEcommerceWeb/Views/Hello/Index.cshtml
<h2>Hello</h2>

HplusEcommerceWeb/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<p>Use this area to provide additional information.</p>

HplusEcommerceWeb/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong>   <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

HplusEcommerceWeb/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Home Page";
}

<div class="jumbotron">
    <div class="jumbotron-content">
        <h1>Chuks Shop</h1>
        <p class="lead">We’re committed to creating products that defy convention, and inspire our customers with pride and trust. In fact, we guarantee every product we sell. If you’re not 100 percent happy with your purchase, you can return it during the first 60 days, no questions asked.</p>
        <p><a href="@Url.Action("Index", "Product")" class="btn btn-primary btn-lg">Our Products &raquo;</a></p>
    </div>
</div>

<div class="row">
    <div class="col-md-4">
        <h2>Philosophy</h2>
        <p>
            Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aenean pulvinar vel metus in vestibulum. Cras placerat libero at quam scelerisque rhoncus. Nam porta, orci eu maximus consequat, leo lectus lacinia neque, non mattis lorem nisi non ligula. Aliquam tristique enim at turpis euismod, vitae iaculis turpis gravida.
        </p>
        <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301865">Learn more &raquo;</a></p>
    </div>
    <div class="col-md-4">
        <h2>History</h2>
        <p>Pellentesque convallis mi at ex aliquet, quis condimentum lacus efficitur. Maecenas at dolor mattis sem vestibulum blandit. Donec pretium, nisl ut interdum fringilla, tellus justo pharetra neque, in porttitor tortor orci a urna. Vivamus at mauris mauris. Etiam nec orci vitae nisi laoreet efficitur. Maecenas rhoncus justo tellus, ut lacinia lacus mollis non.</p>
        <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301866">Learn more &raquo;</a></p>
    </div>
    <div class="col-md-4">
        <h2>People</h2>
        <p>Phasellus molestie egestas lorem, ut imperdiet mauris auctor quis. In lacinia, mi non imperdiet suscipit, odio metus facilisis nunc, sit amet consequat lectus tellus at orci. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Suspendisse potenti.</p>
        <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301867">Learn more &raquo;</a></p>
    </div>
</div>

HplusEcommerceWeb/Views/Login/Index.cshtml
@model HplusEcommerce.Core.Entities.Login
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="container">
    @*<form action="@Request.Url.PathAndQuery" method="post" class="form-signin">*@

        @using (Html.BeginForm("Index", "Login",
            new { ReturnUrl = Request.QueryString["ReturnUrl"] },
            FormMethod.Post, new { @class = "form-signin" }))
        {
            @*@if (ViewBag.Failed == true)
            {
                <div class=" alert alert-danger">Invalid login attempt</div>
            }*@
            if (IsPost)
            {
                <div class=" alert alert-danger">Invalid login attempt</div>
            }
            <h2 class="form-signin-heading">Please sign in</h2>
            @* <label for="username" class="sr-only">Email address</label>
            <input id="username" name="username" class="form-control" placeholder="Email address" autofocus="" value="@(Model?.Username ?? "")">
            *@
            @Html.LabelFor(m => m.Username, "Email address", new { @class = "control-label" })
            @Html.TextBoxFor(m => m.Username, new { @class = "form-control", placeholder = "Email Address", autofocus = "" })
            <label for="password" class="sr-only">Password</label>
            <input type="password" id="password" name="password" class="form-control" placeholder="Password">
            <div class="checkbox">
                <label>
                    <input type="checkbox" value="remember-me"> Remember me
                </label>
            </div>
            <button class="btn btn-lg btn-primary btn-block" type="submit">Sign in</button>
        }


   
</div>

HplusEcommerceWeb/Views/Product/Detail.cshtml
@{
    ViewBag.Title = "Detail";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="container">
    <h3 class="h3">Our Products</h3>
    <div class="row">
        <div class="col-md-offset-4 col-md-4">
            <div class="product-grid">
                <div class="product-image">
                    <a href="#">
                       @*<img src="~/Content/Images/Products/1.jpg"> *@
                        <img src="@ViewBag.Product.ImagePath" />
                    </a>
                    <ul class="social">
                        <li><a href="" data-tip="Quick View"><i class="fa fa-search"></i></a></li>
                        <li><a href="" data-tip="Add to Wishlist"><i class="fa fa-shopping-bag"></i></a></li>
                        <li><a href="" data-tip="Add to Cart"><i class="fa fa-shopping-cart"></i></a></li>
                    </ul>
                    <span class="product-new-label">Sale</span>
                    <span class="product-discount-label">20%</span>
                </div>
                <ul class="rating">
                   @for (int i = 1; i <= ViewBag.Product.StarRating; i++)
                   {
                       <li class="fa fa-star"></li>
                   }

                   @for (int i = ViewBag.Product.StarRating; i < 5; i++)
                   {
                       <li class="fa fa-star disable"></li>
                   }

                </ul>
                <div class="product-content">
                    <h3 class="title"><a href="#">@ViewBag.Product.Name</a></h3>
                    <div class="price">
                        @ViewBag.Product.CurrentPrice
                        <span>@ViewBag.Product.FullPrice</span>
                    </div>
                    <a class="add-to-cart" href="">+ Add To Cart</a>
                </div>
            </div>
        </div>
    </div>
</div>

HplusEcommerceWeb/Views/Product/List.cshtml
@{

    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h3 class="h3">Our Products</h3>
<div class="row">
    <div class="col-md-3 col-sm-6">
        <div class="product-grid">
            <div class="product-image">
                <a href="#">
                    <img src="~/Content/Images/Products/1.jpg">
                </a>
                <ul class="social">
                    <li><a href="" data-tip="Quick View"><i class="fa fa-search"></i></a></li>
                    <li><a href="" data-tip="Add to Wishlist"><i class="fa fa-shopping-bag"></i></a></li>
                    <li><a href="" data-tip="Add to Cart"><i class="fa fa-shopping-cart"></i></a></li>
                </ul>
                <span class="product-new-label">Sale</span>
                <span class="product-discount-label">20%</span>
            </div>
            <ul class="rating">
                <li class="fa fa-star"></li>
                <li class="fa fa-star"></li>
                <li class="fa fa-star"></li>
                <li class="fa fa-star"></li>
                <li class="fa fa-star disable"></li>
            </ul>
            <div class="product-content">
                <h3 class="title"><a href="/product/womens-winter-jacket">Women's Blouse</a></h3>
                <div class="price">
                    $16.00
                    <span>$20.00</span>
                </div>
                <a class="add-to-cart" href="">+ Add To Cart</a>
            </div>
        </div>
    </div>
    <div class="col-md-3 col-sm-6">
        <div class="product-grid">
            <div class="product-image">
                <a href="#">
                    <img src="~/Content/Images/Products/2.jpg">
                </a>
                <ul class="social">
                    <li><a href="" data-tip="Quick View"><i class="fa fa-search"></i></a></li>
                    <li><a href="" data-tip="Add to Wishlist"><i class="fa fa-shopping-bag"></i></a></li>
                    <li><a href="" data-tip="Add to Cart"><i class="fa fa-shopping-cart"></i></a></li>
                </ul>
                <span class="product-new-label">Sale</span>
                <span class="product-discount-label">50%</span>
            </div>
            <ul class="rating">
                <li class="fa fa-star"></li>
                <li class="fa fa-star"></li>
                <li class="fa fa-star"></li>
                <li class="fa fa-star"></li>
                <li class="fa fa-star"></li>
            </ul>
            <div class="product-content">
                <h3 class="title"><a href="#">Men's Plain Tshirt</a></h3>
                <div class="price">
                    $5.00
                    <span>$10.00</span>
                </div>
                <a class="add-to-cart" href="">+ Add To Cart</a>
            </div>
        </div>
    </div>
    <div class="col-md-3 col-sm-6">
        <div class="product-grid">
            <div class="product-image">
                <a href="#">
                    <img src="~/Content/Images/Products/3.jpg">
                </a>
                <ul class="social">
                    <li><a href="" data-tip="Quick View"><i class="fa fa-search"></i></a></li>
                    <li><a href="" data-tip="Add to Wishlist"><i class="fa fa-shopping-bag"></i></a></li>
                    <li><a href="" data-tip="Add to Cart"><i class="fa fa-shopping-cart"></i></a></li>
                </ul>
                <span class="product-new-label">Sale</span>
                <span class="product-discount-label">50%</span>
            </div>
            <ul class="rating">
                <li class="fa fa-star"></li>
                <li class="fa fa-star"></li>
                <li class="fa fa-star"></li>
                <li class="fa fa-star"></li>
                <li class="fa fa-star"></li>
            </ul>
            <div class="product-content">
                <h3 class="title"><a href="#">Men's Plain Tshirt</a></h3>
                <div class="price">
                    $5.00
                    <span>$10.00</span>
                </div>
                <a class="add-to-cart" href="">+ Add To Cart</a>
            </div>
        </div>
    </div>
    <div class="col-md-3 col-sm-6">
        <div class="product-grid">
            <div class="product-image">
                <a href="#">
                    <img src="~/Content/Images/Products/4.jpg">
                </a>
                <ul class="social">
                    <li><a href="" data-tip="Quick View"><i class="fa fa-search"></i></a></li>
                    <li><a href="" data-tip="Add to Wishlist"><i class="fa fa-shopping-bag"></i></a></li>
                    <li><a href="" data-tip="Add to Cart"><i class="fa fa-shopping-cart"></i></a></li>
                </ul>
                <span class="product-new-label">Sale</span>
                <span class="product-discount-label">50%</span>
            </div>
            <ul class="rating">
                <li class="fa fa-star"></li>
                <li class="fa fa-star"></li>
                <li class="fa fa-star"></li>
                <li class="fa fa-star"></li>
                <li class="fa fa-star"></li>
            </ul>
            <div class="product-content">
                <h3 class="title"><a href="#">Men's Plain Tshirt</a></h3>
                <div class="price">
                    $5.00
                    <span>$10.00</span>
                </div>
                <a class="add-to-cart" href="">+ Add To Cart</a>
            </div>
        </div>
    </div>
</div>
<div class="row">
    <div class="col-md-3 col-sm-6">
        <div class="product-grid">
            <div class="product-image">
                <a href="#">
                    <img src="~/Content/Images/Products/5.jpg">
                </a>
                <ul class="social">
                    <li><a href="" data-tip="Quick View"><i class="fa fa-search"></i></a></li>
                    <li><a href="" data-tip="Add to Wishlist"><i class="fa fa-shopping-bag"></i></a></li>
                    <li><a href="" data-tip="Add to Cart"><i class="fa fa-shopping-cart"></i></a></li>
                </ul>
                <span class="product-new-label">Sale</span>
                <span class="product-discount-label">20%</span>
            </div>
            <ul class="rating">
                <li class="fa fa-star"></li>
                <li class="fa fa-star"></li>
                <li class="fa fa-star"></li>
                <li class="fa fa-star"></li>
                <li class="fa fa-star disable"></li>
            </ul>
            <div class="product-content">
                <h3 class="title"><a href="#">Women's Blouse</a></h3>
                <div class="price">
                    $16.00
                    <span>$20.00</span>
                </div>
                <a class="add-to-cart" href="">+ Add To Cart</a>
            </div>
        </div>
    </div>
    <div class="col-md-3 col-sm-6">
        <div class="product-grid">
            <div class="product-image">
                <a href="#">
                    <img src="~/Content/Images/Products/6.jpg">
                </a>
                <ul class="social">
                    <li><a href="" data-tip="Quick View"><i class="fa fa-search"></i></a></li>
                    <li><a href="" data-tip="Add to Wishlist"><i class="fa fa-shopping-bag"></i></a></li>
                    <li><a href="" data-tip="Add to Cart"><i class="fa fa-shopping-cart"></i></a></li>
                </ul>
                <span class="product-new-label">Sale</span>
                <span class="product-discount-label">50%</span>
            </div>
            <ul class="rating">
                <li class="fa fa-star"></li>
                <li class="fa fa-star"></li>
                <li class="fa fa-star"></li>
                <li class="fa fa-star"></li>
                <li class="fa fa-star"></li>
            </ul>
            <div class="product-content">
                <h3 class="title"><a href="#">Men's Plain Tshirt</a></h3>
                <div class="price">
                    $5.00
                    <span>$10.00</span>
                </div>
                <a class="add-to-cart" href="">+ Add To Cart</a>
            </div>
        </div>
    </div>
    <div class="col-md-3 col-sm-6">
        <div class="product-grid">
            <div class="product-image">
                <a href="#">
                    <img src="~/Content/Images/Products/7.jpg">
                </a>
                <ul class="social">
                    <li><a href="" data-tip="Quick View"><i class="fa fa-search"></i></a></li>
                    <li><a href="" data-tip="Add to Wishlist"><i class="fa fa-shopping-bag"></i></a></li>
                    <li><a href="" data-tip="Add to Cart"><i class="fa fa-shopping-cart"></i></a></li>
                </ul>
                <span class="product-new-label">Sale</span>
                <span class="product-discount-label">50%</span>
            </div>
            <ul class="rating">
                <li class="fa fa-star"></li>
                <li class="fa fa-star"></li>
                <li class="fa fa-star"></li>
                <li class="fa fa-star"></li>
                <li class="fa fa-star"></li>
            </ul>
            <div class="product-content">
                <h3 class="title"><a href="#">Men's Plain Tshirt</a></h3>
                <div class="price">
                    $5.00
                    <span>$10.00</span>
                </div>
                <a class="add-to-cart" href="">+ Add To Cart</a>
            </div>
        </div>
    </div>
    <div class="col-md-3 col-sm-6">
        <div class="product-grid">
            <div class="product-image">
                <a href="#">
                    <img src="~/Content/Images/Products/8.jpg">
                </a>
                <ul class="social">
                    <li><a href="" data-tip="Quick View"><i class="fa fa-search"></i></a></li>
                    <li><a href="" data-tip="Add to Wishlist"><i class="fa fa-shopping-bag"></i></a></li>
                    <li><a href="" data-tip="Add to Cart"><i class="fa fa-shopping-cart"></i></a></li>
                </ul>
                <span class="product-new-label">Sale</span>
                <span class="product-discount-label">50%</span>
            </div>
            <ul class="rating">
                <li class="fa fa-star"></li>
                <li class="fa fa-star"></li>
                <li class="fa fa-star"></li>
                <li class="fa fa-star"></li>
                <li class="fa fa-star"></li>
            </ul>
            <div class="product-content">
                <h3 class="title"><a href="#">Men's Plain Tshirt</a></h3>
                <div class="price">
                    $5.00
                    <span>$10.00</span>
                </div>
                <a class="add-to-cart" href="">+ Add To Cart</a>
            </div>
        </div>
    </div>
</div>

HplusEcommerceWeb/Views/Shared/_Layout.cshtml
@helper IconBars(int count) 
{ 
 for (var i = 0; i < count; i++)
 {
        <span class="icon-bar"></span>
 }
}
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")

    <link rel="icon" href="~/Content/images/icons/32x32.png" sizes="32x32">
    <link rel="icon" href="~/Content/images/icons/192x192.png" sizes="192x192">
</head>
<body>
    @*This is the navbar*@
    @Html.Partial("~/Views/Shared/_NavBar.cshtml")
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            @*<p>&copy; H+ Sport @DateTime.Now.Year</p>*@
            <p> @Html.Copyright()
              <a href="http://twitter.com/Clinsage" target="_blank"> @@Clinsage</a>
            </p>
           
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>

HplusEcommerceWeb/Views/Shared/_LayoutNoFooter.cshtml
@helper IconBars(int count) 
{ 
 for (var i = 0; i < count; i++)
 {
        <span class="icon-bar"></span>
 }
}
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")

    <link rel="icon" href="~/Content/images/icons/32x32.png" sizes="32x32">
    <link rel="icon" href="~/Content/images/icons/192x192.png" sizes="192x192">
</head>
<body>
    @Html.Partial("~/Views/Shared/_NavBar.cshtml")

    <div class="container body-content">
        @RenderBody()

    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>

HplusEcommerceWeb/Views/Shared/_NavBar.cshtml
@helper IconBaru(int count)
{
    for (var i = 0; i < count; i++)
    {
        <span class="icon-bar"></span>
    }
}
<div class="navbar navbar-default navbar-fixed-top">
    <div class="container">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                @*<span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>*@
                @IconBaru(2)
            </button>
            <a href='@Url.Action("Index", "Home")' class="navbar-brand">
                <div class="hplus-logo"></div>
            </a>
        </div>
        <div class="navbar-collapse collapse">
            <ul class="nav navbar-nav">
                <li>@Html.ActionLink("Our Products", "Index", "Product")</li>
            </ul>
            <ul class="nav navbar-nav navbar-right">
                <li><a href='@Url.Action("Index", "Cart")'><i class="fa fa-shopping-cart"></i> Cart</a></li>
            </ul>
        </div>
    </div>
</div>